CREATE TABLE IF NOT EXISTS organization (
    id SERIAL PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    TITLE VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    WEBSITE VARCHAR(255),
    ACTIVE BOOLEAN default true,
    SLOGAN VARCHAR(255),
    APP_SERVER VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRTD_SESSION_ID VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    ACTIVE BOOLEAN default true,
    ORG_ID BIGINT,
    ADDRESS VARCHAR(255),
    CONTACT_INFO VARCHAR(255),
    LEFT_LOGO VARCHAR(255),
    RIGHT_LOGO VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CRTD_SESSION_ID VARCHAR(255),
    FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(id)
);

CREATE TABLE employee (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100) UNIQUE,
    password VARCHAR(255),
    active BOOLEAN default true,
    created_by VARCHAR(255),
    created_at TIMESTAMP,
    last_modified_by VARCHAR(255),
    last_modified_at TIMESTAMP
);

CREATE TABLE token (
    id SERIAL PRIMARY KEY,
    token VARCHAR(255) UNIQUE,
    token_type VARCHAR(50),
    revoked BOOLEAN,
    expired BOOLEAN,
    employee_id INTEGER REFERENCES employee(id)
);


CREATE SEQUENCE employee_seq START 1001;
CREATE SEQUENCE token_seq START 1;